apiVersion: v1
kind: Service
metadata:
  name: dnsmasq-service
  namespace: dnsmasq-service
  labels:
    app: dnsmasq-service
spec:
  ports:
    - name: dns
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dhcp  
      protocol: UDP
      port: 67
      targetPort: 67
  selector:
    app: dnsmasq-service
