apiVersion: v1
kind: Namespace
metadata:
  name: whoami-app
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: helm-dependency
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    